### PR TITLE
CI: upgrade runner to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by kleisauke**
- Compile with GCC 11 and Clang 14.
- Remove redundant PPAs.
- Use system provided Meson.
- Update LeakSanitizer suppressions.

Note that this GitHub Actions runner is still in beta phase, so we might have to wait.

### CODE REVIEW

**Comment by jcupitt** [comment]
Hello Kleis, this looks good, do you think we should merge? Or wait a little longer?

**Comment by kleisauke** [comment]
I think it's probably safe to land, but I'm not sure if the ASan / UBsan build would succeed, so I think I'll re-base this after PR #2853 lands.

**Comment by jcupitt** [comment]
OK, I merged #2853

**Comment by jcupitt** [comment]
LGTM!

**Pull request merged**
