### PR TITLE
revise gifload to improve dispose handling

### PR DESCRIPTION
**Pull request by jcupitt**
Revise gifload to improve dispose handling.

This is the PR in https://github.com/libvips/libvips/pull/1549 with a few small changes:

- fix merge conflicts
- revise formatting to match libvips conventions (width 8 hard tabs etc.)
- fix byte order dependency with GUINT32_TO_BE()
- speed up clear to transparent loop

### CODE REVIEW

**Comment by alon-ne** [comment]
Tests pass and everything looks good to me 👍

**Comment by jcupitt** [comment]
Great! Thanks again.

**Comment by alon-ne** [comment]
Very cool, thanks for the merge. Any idea when there's gonna be an official release with this fix? We can help if needed

**Comment by jcupitt** [comment]
It's in 8.10, so a few months, probably.

**Comment by jcupitt** [comment]
I found a bug: https://github.com/libvips/libvips/commit/3ad3c30ab4f3791e438558e4a9cf5481da2f1156

In case you have this code in production.

**Pull request merged**
