### PR TITLE
try putting version numbers into the meson summary

### PR DESCRIPTION
**Pull request by jcupitt**
I often find myself checking the version number of detected packages, it might be useful to have this in the summary.

Sample output:

```
    enable RAD load/save              : YES
    enable Analyze7 load/save         : YES
    enable PPM load/save              : YES
    enable GIF load                   : YES

  Optional external packages
    use fftw for FFTs                 : YES 3.3.10
    SIMD support with highway         : YES 1.0.7
    accelerate loops with ORC         : NO NO
    ICC profile support with lcms     : YES 2.14
    zlib                              : YES 1.2.13
    text rendering with pangocairo    : YES 1.51.0
    font file support with fontconfig : YES 2.14.2
    EXIF metadata support with libexif: YES 0.6.24

  External image format libraries
    JPEG load/save with libjpeg       : YES 2.1.5
    JXL load/save with libjxl         : YES 0.7.0 dynamic module: YES
    JPEG2000 load/save with OpenJPEG  : YES 2.5.0
    PNG load/save with libspng        : NO unknown
    PNG load/save with libpng         : YES 1.6.40
    selected quantisation package     : imagequant 2.17.0
    TIFF load/save with libtiff       : YES 4.5.1
```

etc.

It could be a bit prettier, and it does make the output rather busy. Any thoughts?

### CODE REVIEW

**Comment by jcupitt** [comment]
Now looks like:

```
  Optional external packages
    FFTs with fftw                    : YES	fftw3 3.3.10
    SIMD support with Highway         : YES	libhwy 1.0.7
    accelerate loops with ORC         : NO	
    ICC profile support with lcms     : YES	lcms2 2.14
    deflate compression with zlib     : YES	zlib 1.2.13
    text rendering with pangocairo    : YES	pangocairo 1.51.0
    font file support with fontconfig : YES	fontconfig 2.14.2
    EXIF metadata support with libexif: YES	libexif 0.6.24
```

So it's a bit less noisy.

**Comment by kleisauke** [comment]
How about this changeset?:
https://github.com/libvips/libvips/compare/version-numbers-in-mesonh-summary...kleisauke:meson-dependency-versions

That would result in:
```
vips 8.16.0

  Dependency versions
    fftw3                             : 3.3.10
    libhwy                            : 1.0.7
    lcms2                             : 2.15
    zlib                              : 1.2.13
    pangocairo                        : 1.51.0
    fontconfig                        : 2.14.2
    libexif                           : 0.6.24
    libjpeg                           : 2.1.4
    libjxl                            : 0.8.2
    libopenjp2                        : 2.5.0
    spng                              : 0.7.4
    imagequant                        : 4.0.3
    libtiff-4                         : 4.4.0
    libarchive                        : 3.7.1
    libheif                           : 1.16.2
    libwebp                           : 1.3.2
    poppler-glib                      : 23.08.0
    librsvg-2.0                       : 2.57.0
    OpenEXR                           : 3.1.10
    openslide                         : 3.4.1
    matio                             : 1.5.26
    niftiio                           : 3.0.1
    cfitsio                           : 4.3.0
    cgif                              : 0.3.2
    MagickCore                        : 7.1.1

  Build options
    enable debug                      : NO
    enable deprecated                 : YES
    enable modules                    : YES
    enable gtk-doc                    : NO
    enable doxygen                    : NO
    enable introspection              : YES
    enable examples                   : YES
    enable cplusplus                  : YES
    enable RAD load/save              : YES
    enable Analyze7 load/save         : YES
    enable PPM load/save              : YES
    enable GIF load                   : YES

  Optional external packages
    FFTs with fftw3                   : YES
    SIMD support with libhwy          : YES
    ICC profile support with lcms2    : YES
    deflate compression with zlib     : YES
    text rendering with pangocairo    : YES
    font file support with fontconfig : YES
    EXIF metadata support with libexif: YES

  External image format libraries
    JPEG load/save with libjpeg       : YES
    JXL load/save with libjxl         : YES (dynamic module: YES)
    JPEG2000 load/save with libopenjp2: YES
    PNG load/save with spng           : YES
    image quantisation with imagequant: YES
    TIFF load/save with libtiff-4     : YES
    image pyramid save with libarchive: YES
    HEIC/AVIF load/save with libheif  : YES (dynamic module: YES)
    WebP load/save with libwebp       : YES
    PDF load with poppler-glib        : YES (dynamic module: YES)
    SVG load with librsvg-2.0         : YES
    EXR load with OpenEXR             : YES
    WSI load with openslide           : YES
    Matlab load with matio            : YES
    NIfTI load/save with niftiio      : YES
    FITS load/save with cfitsio       : YES
    GIF save with cgif                : YES
    Magick load/save with MagickCore  : YES (dynamic module: YES)
```

(but perhaps that's too long?)

**Comment by jcupitt** [comment]
Oh that's nice.

We could print `libvips_deps` instead, that way we'd catch all the external dependencies. I had a quick go.

**Comment by jcupitt** [comment]
So it now looks like this:

```
vips 8.16.0

  External dependency versions
    glib-2.0                          : 2.78.0
    gio-2.0                           : 2.78.0
    gobject-2.0                       : 2.78.0
    gmodule-no-export-2.0             : 2.78.0
    expat                             : 2.5.0
    zlib                              : 1.2.13
    libarchive                        : 3.6.2
    fftw3                             : 3.3.10
    cfitsio                           : 4.2.0
    imagequant                        : 2.17.0
    cgif                              : 0.3.2
    libexif                           : 0.6.24
    libjpeg                           : 2.1.5
    libpng                            : 1.6.40
    libwebp                           : 1.2.4
    libwebpmux                        : 1.2.4
    libwebpdemux                      : 1.2.4
    pangocairo                        : 1.51.0
    pangoft2                          : 1.51.0
    fontconfig                        : 2.14.2
    libtiff-4                         : 4.5.1
    librsvg-2.0                       : 2.54.7
    cairo                             : 1.18.0
    matio                             : 1.5.23
    lcms2                             : 2.14
    OpenEXR                           : 3.1.5
    libopenjp2                        : 2.5.0
    libhwy                            : 1.0.7
    niftiio                           : 3.0.1

  Build options
    enable debug                      : YES
    enable deprecated                 : YES
    enable modules                    : YES
... etc.
```

**Comment by kleisauke** [comment]
Ah, that's indeed neater. LGTM!

**Review by kleisauke — APPROVED** [review]

**Pull request merged**
