### PR TITLE
move tiff decompress outside lock

### PR DESCRIPTION
**Pull request by jcupitt**
Most time in TIFF read is spent in decompression. If we move this
outside the lock, we can get a useful speedup.

This commit adds the machinery to move the lock to before decompress, so
jp2k decompression is now threaded.

Before:

```
$ vips copy wtc.jpg x.tif[tile,compression=jp2k]
$ time vips avg x.tif
117.249845
real	0m15.085s
user	0m16.155s
sys	0m0.109s
```

After:

```
$ time vips avg x.tif
117.249845
real	0m1.207s
user	0m18.384s
sys	0m0.369s
```

### CODE REVIEW

**Comment by jcupitt** [comment]
See: https://github.com/libvips/libvips/issues/2945

To do:

- [ ] same for jpeg decompress (see openslide for example code)
- [ ] possibly deflate as well? lzw?
- [ ] same for TIFF save

**Comment by jcupitt** [comment]
I added JPEG decompress too. Before:

```
$ time vips avg x.tif
117.855086
real	0m0.796s
user	0m1.114s
sys	0m0.133s
```

After:

```
$ time vips avg x.tif
117.855086
real	0m0.319s
user	0m1.185s
sys	0m0.150s
```

So maybe 2.5x faster. That's with a 10k a 10k RGB JPEG tiff, with 256x256 tiles.

**Comment by jcupitt** [comment]
No need to add this to tiff write, that already runs in a background thread.

**Comment by jcupitt** [comment]
It still seems to be slower than openslide load: 

```python
#!/usr/bin/python3

import sys
import time
import pyvips

start = time.time()
image = pyvips.Image.openslideload(sys.argv[1])
print(f"avg = {image.avg()}")
end = time.time()
print(f"openslide took {end - start:.2f}s")

start = time.time()
image = pyvips.Image.tiffload(sys.argv[1])
print(f"avg = {image.avg()}")
end = time.time()
print(f"tiffload took {end - start:.2f}s")
```

With git master I see:

```
$ vips copy ../wtc.jpg x.tif[compression=jpeg,tile]
$ ./avg.py x.tif
avg = 152.14133278659983
openslide took 0.14s
avg = 117.85511038213312
tiffload took 1.43s
```

With this PR it's a bit better:

```
$ ./avg.py x.tif
avg = 152.14133278659983
openslide took 0.14s
avg = 117.85511038213312
tiffload took 0.63s
```

Larger tiles make tiffload faster, but openslide slower:

```
$ vips copy ../wtc.jpg x.tif[compression=jpeg,tile,tile-width=512,tile-height=512]
$ ./avg.py x.tif
avg = 152.14131365400138
openslide took 0.47s
avg = 117.85508487200184
tiffload took 0.21s
```

So I suppose it's overhead in the tile cache.

**Comment by jcupitt** [comment]
I tried adjusting the libvips threadpool:

```python
#!/usr/bin/python3

import sys
import time
import pyvips

start = time.time()
image = pyvips.Image.openslideload(sys.argv[1])
a = image.avg() 
openslide = time.time() - start

start = time.time()
image = pyvips.Image.tiffload(sys.argv[1])
a = image.avg()
tiff = time.time() - start

print(f"{openslide:.2f}, {tiff:.2f}")
```

```
$ for i in {1..32}; do echo -n "$i, "; VIPS_CONCURRENCY=$i ./avg.py x.tif; done
1, 2.17, 0.75
2, 1.13, 0.54
3, 0.77, 0.51
4, 0.58, 0.48
5, 0.47, 0.61
6, 0.40, 0.63
7, 0.34, 0.59
8, 0.31, 0.61
9, 0.28, 0.58
10, 0.25, 0.51
11, 0.23, 0.58
12, 0.22, 0.54
13, 0.20, 0.55
14, 0.20, 0.56
15, 0.19, 0.60
16, 0.19, 0.58
17, 0.18, 0.56
18, 0.17, 0.63
19, 0.16, 0.60
20, 0.17, 0.64
21, 0.17, 0.65
22, 0.16, 0.64
23, 0.15, 0.60
24, 0.15, 0.60
25, 0.15, 0.62
26, 0.15, 0.62
27, 0.15, 0.66
28, 0.15, 0.63
29, 0.14, 0.65
30, 0.15, 0.65
31, 0.14, 0.67
32, 0.15, 0.70
```

So openslide scales well with more threads, tiffload hardly scales at all.

**Comment by jcupitt** [comment]
Oh heh it's just the demand style. `avg` uses `THINSTRIP`, so it's scanning the TIFF file using one pixel high tiles. Each avg tile will therefore hit every TIFF tile in a row! We're forcing sequential decode.

I added:

```C
        if( vips_image_pipelinev( statistic->ready, 
                VIPS_DEMAND_STYLE_SMALLTILE, NULL ) )
                return( -1 );
```

To `vips_statistic_build` and I now see:

```
$ for i in {1..32}; do echo -n "$i, "; VIPS_CONCURRENCY=$i ./avg.py x.tif; done
1, 2.23, 0.52
2, 1.13, 0.29
3, 0.76, 0.20
4, 0.58, 0.15
5, 0.47, 0.13
6, 0.40, 0.10
7, 0.34, 0.09
8, 0.31, 0.08
9, 0.27, 0.07
10, 0.25, 0.07
11, 0.23, 0.06
12, 0.21, 0.06
13, 0.20, 0.05
14, 0.19, 0.05
15, 0.19, 0.05
16, 0.18, 0.05
17, 0.20, 0.05
18, 0.17, 0.04
19, 0.18, 0.04
20, 0.17, 0.04
21, 0.17, 0.04
22, 0.17, 0.04
23, 0.16, 0.04
24, 0.16, 0.04
25, 0.15, 0.04
26, 0.15, 0.04
27, 0.15, 0.04
28, 0.15, 0.04
29, 0.15, 0.04
30, 0.15, 0.04
31, 0.15, 0.04
32, 0.15, 0.04
```

So libvips tiffload is /much/ faster than openslide load, phew.

**Comment by jcupitt** [comment]
OK, all done.

Before:

```
$ vips copy wtc.jpg x.tif[tile,compression=jp2k]
$ time vips avg x.tif
117.249845
real	0m15.085s
user	0m16.155s
sys	0m0.109s
$ vips copy wtc.jpg x.tif[tile,compression=jpeg]
$ time vips avg x.tif
117.855086
real	0m0.796s
user	0m1.114s
sys	0m0.133s
```

After:

```
$ vips copy wtc.jpg x.tif[tile,compression=jp2k]
$ time vips avg x.tif
117.249845
real	0m0.561s
user	0m16.679s
sys	0m0.149s

$ vips copy wtc.jpg x.tif[tile,compression=jpeg]
$ time vips avg x.tif
117.855110
real	0m0.065s
user	0m0.790s
sys	0m0.093s
```

**Comment by euzada** [comment]
Hi @jcupitt , I am using pyvips with libvips latest version available on windows from the windows binary to build an arrayjoin and save it as oem-tiff with jpeg compression. The save takes almost 20x longer when the compression jpeg is set compared to none. For example none can finish in 1 minutes while jpeg[Q=75] default (not set) can take up to 20minutes. I am just wondering if the windows binary use the encoding and decoding of jpeg from libtiff or if this commit applied to windows binary. Thank you.

**Comment by jcupitt** [comment]
Hi @euzada, this PR was for tiff read. We could do the same for tiff write, but no one's done the work yet. Maybe next version.

**Comment by euzada** [comment]
Thank you for your quick answer. That's will be great as writing takes now long time. I will do some test with different compression but basically any compression is taking long time. The fastest writing is obviously v format, than tiff with no compression. I wish I can contribute more to this amazing lib but I am not programmer, unfortunately.

**Comment by euzada** [comment]
Hi @jcupitt, is there any plan to improve the tiff write similar to the tiff read in the next version? I wonder if it is an active PR.  Thank you.

**Comment by jcupitt** [comment]
I've been working (very slowly) on improving `dzsave`. I might look at TIFF write after that, if no one else does.

**Comment by euzada** [comment]
That's great. The only way I can help is by doing some testing if needed. I look forward to the improvement in writing compressed tiff faster.
Thank you again, @jcupitt, for your quick response, and good luck with dzsave.

**Pull request merged**
