### PR TITLE
early feedback: loading and storing via FILE

### PR DESCRIPTION
**Pull request by srijs**
For my use-case, I'd like to be able to load and save images from/to stdin/stdout, similar to what's been described in #803.

I understand that eventually you'd like to see something based on `GFile` or `GInputStream`/`GOutputStream`, however I'm just starting out on this codebase and didn't want to pick such a large task just yet.

As a compromise, I've started to implement loading and storing functions that can deal with standard `FILE` objects.

What I'm mainly looking for here is to get early feedback on the approach, before I start to change more code.

Let me know what you think!

### CODE REVIEW

**Comment by jcupitt** [comment]
Hello @srijs, this is very interesting, sorry I've not responded. I'm horribly busy for the next 10 days or so, but I'll looks at this after that's done.

**Comment by jcupitt** [comment]
I'd really like to do something like this for 8.8, but I think this is the wrong approach, sorry :( For example, you won't be able to write to an http stream with this, which has to be one of the main advantages.

I think we should add simple input and output stream classes. https://github.com/lovell/sharp/issues/30 outlines `VipsStream`, `VipsStreamInput` and `VipsStreamOutput`. They are only a few 100 lines of code, it's nothing like the complexity of `GFile` etc. (phew!). Here's the implementation from 2014:

https://github.com/libvips/libvips/blob/load-from-stream/libvips/iofuncs/stream.c

The feature we need that was missing last time we tried this is rewind: the input class needs to keep the first part of the image data it reads (the header) in a cache, and resupply it if necessary. This would let us open the same stream twice, once to get the header, and a second time to get the pixels. Load operations will need some way to signal to the input object when they are parsing the header. 

We then need to rework PNG load/save (to pick an example) to run on top of `VipsStream`, and reimplement the current file and memory load/save as tiny wrappers.

Here's how that was done in 2014: 

https://github.com/libvips/libvips/blob/load-from-stream/libvips/foreign/vipspng.c#L768

**Comment by apuckey** [comment]
Hi,

I have been playing around with the php extensions and libvips. very impressed with the ram use however not having streams almost defeats the purpose when you have to load a 2gb file in ram to process :D 

Could you not just use a library like libcurl to handle the streaming to/from http streams ? added bonus is it works on windows as well using the same code i believe.

Ignore if you have already thought of it and discounted it. I'm not a c guru so could be totally off base here :)

cheers

**Comment by jcupitt** [comment]
Hiya,

It's not quite as bad as it sounds -- for example, with a JPG , you only need to load the compressed image into memory. libvips will process it as:

```
read -> jpeg in memory -> 128 scanline buffer -> process -> 
    128 scanline buffer -> jpg in memory -> write
```

So you only need the memory for a few lines of uncompressed pixels. PNG will see a saving too, since images are typically 30% smaller than uncompressed pixels. It won't help much for TIFF I guess.

Of course you can do:

```
read to file in /tmp -> 128 scanline buffer -> process -> 
    128 scanline buffer -> file in /tmp -> write
```

Assuming you have enough `tmp`. It's actually no slower, on linux anyway.

True streaming, where you never need to have the entire compressed image buffered in memory, is on the wishlist but has not happened yet, and won't in the short-term.

**Comment by jcupitt** [comment]
Here's a PR that adds true streaming support:

https://github.com/libvips/libvips/pull/1443

Though only for jpg at the moment. Any comments very welcome.

**Pull request closed without merging**
