### PR TITLE
Improve scRGB support

### PR DESCRIPTION
**Pull request by jcupitt**
Handling of scRGB has a couple of issues:

- When converting scRGB to and from sRGB and RGB16 we are changing the image gamma, so any profiles on the image will break. They need to be removed.

- Conversion for saveable RGB did not handle scRGB

See https://github.com/libvips/libvips/issues/3621

Using the [test image from the linked issue](https://github.com/libvips/libvips/files/12422094/tiff7.tiff.zip) (a float TIFF saved by photoshop) with this PR I can now run:

```
$ vips copy tiff7.tiff x.png
```

To make:

x

Though this makes a black image:

```
$ vips icc_transform tiff7.tiff x.png srgb
```

So I suppose `icc_transform` does not handle scRGB correctly. I'll mark this as a draft until this extra issue is resolved too.

### CODE REVIEW

**Comment by kleisauke** [comment]
Issue #2858 and its test case may also be relevant here.

**Comment by jcupitt** [comment]
The test case in #2858 works with this PR:

```
$ vips colourspace k2.jpg x.v scrgb
$ vips copy x.v x.jpg 
```

**Comment by jcupitt** [comment]
Ah, the `icc_import` failure is because we don't support linear RGB profiles, we only have 8 and 16-bit device space. I think that this should probably be a separate issue.

**Comment by jcupitt** [comment]
> requires other changes to let jxlsave encode

Ugh, this will take a while. We should get https://github.com/libvips/libvips/pull/3712 in at the same time.

Shall we park this for 8.16? It would delay release by quite a while.

**Comment by kleisauke** [comment]
I had a very quick attempt with commit https://github.com/kleisauke/libvips/commit/d7daf546071a40f45cf39e300d8a298c0cf39fe3, and it appears to work; however, jxlload is unable to decode these images due to:
https://github.com/libjxl/libjxl/blob/e37516e7a7494f49613ac2cde1b58dbc06e52e62/lib/jxl/decode.cc#L2302-L2304

To decode these extra channels, you apparently also need to call `JxlDecoderExtraChannelBufferSize()` / `JxlDecoderSetExtraChannelBuffer()`. A similar issue occurs when trying to decode the CMYK + Alpha test image from the libjxl conformance repository:
https://github.com/libjxl/conformance/blob/master/testcases/cmyk_layers/input.jxl

**Comment by kleisauke** [comment]
> Shall we park this for 8.16? It would delay release by quite a while.

I think this PR would still be useful to have for 8.15. How about this commit?:
https://github.com/kleisauke/libvips/commit/59e8b6c98444f4f58a2a892d87f939ec33d29531

That would mimic `VIPS_SAVEABLE_RGBA` in jxlsave and still allow it to operate on scRGB images.

> To decode these extra channels, you apparently also need to call `JxlDecoderExtraChannelBufferSize()` / `JxlDecoderSetExtraChannelBuffer()`.

On a somewhat tangent, it seems that the new streaming encode API in libjxl uses a callback-based approach, rather than a  'push'-based tile/scanline approach (used in libraries like libtiff),
https://libjxl.readthedocs.io/en/latest/api_encoder.html#_CPPv426JxlChunkedFrameInputSource

**Comment by jcupitt** [comment]
OK, let's do that, and I suppose leave the jxl load / save reworking for 8.16?

**Comment by kleisauke** [comment]
Indeed, let's defer the jxl load/save rework to the 8.16 cycle.

**Review by kleisauke — APPROVED** [review]

**Pull request merged**
