### PR TITLE
Never set the PFM header to little endian

### LINKED ISSUE #4241: pfm formats test fails on s390x
## Bug report

**Describe the bug**
pfm formats test fails on s390x

**To Reproduce**
1. Build on s390x
2. Run tests

**Expected behavior**
Tests succeed.

**Actual behavior**
```
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
testing sample.jpg v ... ok
testing sample.jpg tif ... ok
testing sample.jpg tif[compression=jpeg] ... ok
testing sample.jpg tif[compression=deflate] ... ok
testing sample.jpg tif[compression=packbits] ... ok
testing sample.jpg tif[compression=jpeg,tile] ... ok
testing sample.jpg tif[compression=jpeg,tile,pyramid] ... ok
testing sample.jpg png ... ok
testing sample.jpg png[compression=9,interlace=1] ... ok
testing sample.jpg png[palette,colours=256,Q=100,dither=0,interlace=1] ... ok
testing sample.jpg jpg ... ok
testing sample.jpg webp ... ok
testing sample.jpg ppm ... ok
testing sample.jpg pfm ... save / load difference is 242.000000
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Screenshots**
t1 pfm

**Environment**
(please complete the following information)
 - OS: Fedora 41, s390x
 - Vips: 8.16.0

**Additional context**
https://koji.fedoraproject.org/koji/taskinfo?taskID=125461429

I'm working on debugging the issue now.

### PR DESCRIPTION
**Pull request by agoode**
PFM files are always written in big endian:
https://github.com/libvips/libvips/blob/master/libvips/foreign/ppmsave.c#L459

But the header is set to little endian if on a big endian machine (!) https://github.com/libvips/libvips/blob/master/libvips/foreign/ppmsave.c#L414-L415

Fixes #4241.

### CODE REVIEW

**Comment by jcupitt** [comment]
!!!! Well, that was pretty dumb. Thank you very much for finding this @agoode.

Let's put this in 8.16 (stable branch), it seems like a straightforward change.

**Comment by jcupitt** [comment]
Ooop, more dumbness, I messed that up. 

Fixed with https://github.com/libvips/libvips/commit/f06db0f9161aa98a026dc7705eef3e33874316d6 I hope.

**Comment by kleisauke** [comment]
Retargeting PRs to stable branches can be somewhat cumbersome. :(

Hopefully PR #4162 makes the process of backporting commits to these branches a bit smoother.

**Comment by agoode** [comment]
Will this get merged back to master eventually?

**Comment by jcupitt** [comment]
Yes, we always merge stable branches to master, I just hadn't got around to it. I'll do it now.

**Pull request merged**
