### PR TITLE
add libjxl ICC and scRGB support

### PR DESCRIPTION
**Pull request by jcupitt**
see https://github.com/libvips/libvips/issues/2568

### CODE REVIEW

**Comment by jcupitt** [comment]
There's a branch here with the start of exif and xmp support, but libjxl have not released this yet, so we should wait.

**Comment by jcupitt** [comment]
I'm still not sure if this is correct, but it's certainly better than what we had before.

I'm inclined to merge this so we can release libvips 8.13, and do another round of JXL improvements when the next version of libjxl is released. What do you think?

**Comment by f1ac** [comment]
Totally agree, I see no issues with this PR.

**Comment by jcupitt** [comment]
OK, let's do it! Thank you for pushing for this and for doing the testing.

**Pull request merged**
