### PR TITLE
Improve fuzz targets and oss-fuzz integration

### PR DESCRIPTION
**Pull request by omira-sch**
It adds support to integrate libvips into google's fuzzing platform oss-fuzz. We think It would be beneficial for the community to take advantage of continuous fuzzing the code to find vulnerabilities. 

We tried to follow the official guide for new projects described here https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md. We already have one almost ready [PR to submit to oss-fuzz](https://github.com/google/oss-fuzz/compare/google:master...omira-sch:libvips).

Besides oss-fuzz, we have improved the CI build to compile with ASAN and run the test suite. This way we have already discovered some issues (#1263). We have also written 5 new fuzz targets that can be executed alone, e.g. under LibFuzzer.

More comments in the commits.

This PR is complete but we would like to gather feedback from you people. We made some design decisions in our way that we will like to discuss.

### CODE REVIEW

**Comment by jcupitt** [comment]
Hello @omira-sch, this is great, I was planning to look at oss-fuzz again once libvips 8.8 was done. You probably saw https://github.com/libvips/libvips/issues/695

I'll look over this PR in the next few days.

**Comment by omira-sch** [comment]
> I was planning to look at oss-fuzz again once libvips 8.8 was done. You probably saw #695

I was not aware it was on the roadmap. I read #695 when I started to think about this project months ago. I missed comments posted on February. My apologies!

> I'll look over this PR in the next few days.

Thanks for considering it.

**Comment by jcupitt** [comment]
Update: let's get 8.7 out of the door and do oss-fuzz integration in 8.8.

**Comment by jcupitt** [comment]
OK, I've read it through and it all looks very neat. Fuzzing seems much cleaner than when I looked at it a couple of years ago! Or perhaps I did a terrible job heh.

Nice job!

I'll see if I can get it running locally before we merge.

**Comment by omira-sch** [comment]
Thank you. I have rebased my branch to HEAD. I also have added two new commits https://github.com/libvips/libvips/pull/1264/commits/50ce012520ebdffb4a4e90b9eaf8fad599b5d498 and https://github.com/libvips/libvips/pull/1264/commits/4b1c49eb95514d68a4ba83dcb85fce0e1703999f. Basically, to configure ASAN to ignore memory leaks during the python tests. I guess those leaks are not related to libvips codebase. Now the travis job for the clang + ASAN compilation is green as well.

Some random notes:
- I included 5 fuzzers trying to maximize the coverage. All fuzzers have in common the image loading stuff (vips_image_new_from_buffer) for all files formats supported by libvips, and then they are focused in one specific operation: transcoding to common formats (PEG, PNG, WEBP), sharpen, and thumbnail. Thumbnail is by far the most complex operation, so I skip big image files for it.
- The fuzzers are supposed to run in google's [clusterfuzz](https://github.com/google/oss-fuzz/blob/master/docs/clusterfuzz.md). In the [build script](https://github.com/google/oss-fuzz/compare/google:master...omira-sch:libvips#diff-e5ca80c6ac02109130303cc8ef68d1faR31), I bootstrap all of them with the same [corpus](http://lcamtuf.coredump.cx/afl/demo/). 
- When clusterfuzz detects a failure, it sends you the report by email, attaching the image file that generated the crash (testcase). There is a directory "corpus" inside fuzz where you can commit the testcases and travis will run the fuzzers against them (as part of the "make test", see https://travis-ci.org/libvips/libvips/jobs/559182897#L2643). The fuzzers are run in simple-standalone mode in travis, meaning that they read the corpus directory and run the fuzzing functions one time per input file. This way you can work on the fixes until all checks pass OK.
- Storing previous testcases in the corpus also allows you to perform regression-testing.

**Comment by jcupitt** [comment]
All very nice, let's go for it!

Thank you for working on this important improvement, Oscar. I owe you a number of beers.

**Pull request merged**
