### PR TITLE
Implement Header Sniffing For Magickload Tga

### LINKED ISSUE #2527: Add a TGA sniffer
The imagemagick TGA coder doesn't have a sniffer, so `magickload_buffer` (and `new_from_buffer`) can't load TGAs.

Fix: add a TGA sniffer to `magick_sniff()`:

https://github.com/libvips/libvips/blob/master/libvips/foreign/magick.c#L55-L73

Referring discussion: https://github.com/libvips/libvips/discussions/2524

Reproducer:

```python
#!/usr/bin/python3

import sys
import pyvips

with open(sys.argv[1], "rb") as f:
    data = f.read()
    
image = pyvips.Image.magickload_buffer(data)

new_data = image.magicksave_buffer(format=sys.argv[2])
print(f"written {len(new_data)} bytes")
```

With 8.12 you see:

```
$ ./try331.py  ~/pics/k2.jpg png
written 3218995 bytes
```

Since PNG and JPG have sniffers, but:

```
$ ./try331.py  ~/pics/CapricornCoasts.tga png
Traceback (most recent call last):
...
  magick2vips: libMagick error: no decode delegate for this image format `' @ error/blob.c/BlobToImage/363
magick2vips: unable to read buffer
```

Since there's no TGA sniffer.

### PR DESCRIPTION
**Pull request by Moggers**
Implements (somewhat naive) header sniffing for TGA files by validating the color map and image data type fields of the header.

```
➜  vipsheader CapricornCoasts.tga
CapricornCoasts.tga: 3072x1330 uchar, 4 bands, srgb, magickload
➜  vipsheader Meropis.tga
Meropis.tga: 2548x1744 uchar, 4 bands, srgb, magickload
```

Closes #2527

### CODE REVIEW

**Comment by Moggers** [comment]
@jcupitt as discussed yesterday

**Comment by jcupitt** [comment]
Oh, nice!

We're in feature-freeze for the 8.12 release right now. Once this is done, let's merge it (and the orientation PR) in the 8.13 cycle.

**Comment by jcupitt** [comment]
I think this look OK even though it's still tagged as draft. OK to merge for 8.12?

**Comment by jcupitt** [comment]
Actually, how about removing the SGI test file? libvips has no special handling for this file type, so it's really exercising imagemagick, which is probably out of scope for us. Or did you intend to add an SGI sniffer too?

**Comment by Moggers** [comment]
No on the SGI sniffer. The SGI test I added as my first implementation of the TGA sniffer had a furphy that caused it to erroneously detect SGIs as TGAs and broke the SGI loading, none of the existing tests picked it up and I didn't find it until I actually went to use it, so I figured I'd add the SGI test to verify that the sniffing isn't too broad. I can remove it if you want.

**Comment by jcupitt** [comment]
OK, merged! This will be in 8.12, thank you very much for doing this work.

**Pull request merged**
