### PR TITLE
libheif: expose speed parameter

### PR DESCRIPTION
**Pull request by lovell**
This parameter is currently only used for AV1 compression.

By limiting to a 0-8 range we can provide a consistent API for both the aom and rav1e encoders. (The rav1e encoder accepts speed values of 9 and 10 but these use 64x64 blocks and fast key frame detection, which are concepts more relevant to low quality video than still images.)

As discussed in #1788

(The SVT-AV1 encoder, not yet available via libheif, also uses the same 0 slowest to 8 fastest range for its `EncoderMode` speed setting so this approach is hopefully future proof for that too.)

### CODE REVIEW

**Comment by jcupitt** [comment]
Looks good!

**Comment by lovell** [comment]
@jcupitt Would you consider backporting this to the 8.10(.2) branch? I'm planning to add libheif+aom to the binaries provided by sharp and exposing control over the speed and therefore CPU time might help reduce the planet's energy consumption by a noticeable amount as everyone rushes to re-encode all their images as AVIF.

**Comment by jcupitt** [comment]
It's usually bad to add API to stable, but I agree this seems like a special case. Let's do it!

**Comment by kleisauke** [comment]
For reference, libavif takes a different approach and remaps the speed values 0-10 to CPU used (0-8) and aom usage (good quality / real-time mode), see:
https://github.com/AOMediaCodec/libavif/blob/3f2bf9512057e33e0746619b58f8cefb3ff5d1a4/src/codec_aom.c#L355-L377

**Pull request merged**
