### PR TITLE
Deduplicate `--vips-config` with the build summary

### PR DESCRIPTION
**Pull request by kleisauke**
`vips --vips-config` difference:

```diff
@@ -13,25 +13,25 @@ text rendering with pangocairo: true
 font file support with fontconfig: true
 EXIF metadata support with libexif: true
 JPEG load/save with libjpeg: true
-JXL load/save with libjxl: true (dynamic module: true)
+JXL load/save with libjxl: true (dynamic module)
 JPEG2000 load/save with OpenJPEG: true
 PNG load/save with libspng: true
 PNG load/save with libpng: false
 selected quantisation package: imagequant
 TIFF load/save with libtiff: true
 image pyramid save with libgsf: true
-HEIC/AVIF load/save with libheif: true (dynamic module: true)
+HEIC/AVIF load/save with libheif: true (dynamic module)
 WebP load/save with libwebp: true
 PDF load with PDFium: false
-PDF load with poppler-glib: true (dynamic module: true)
+PDF load with poppler-glib: true (dynamic module)
 SVG load with librsvg: true
 EXR load with OpenEXR: true
-OpenSlide load: true (dynamic module: true)
+OpenSlide load: true (dynamic module)
 Matlab load with libmatio: true
 NIfTI load/save with niftiio: true
 FITS load/save with cfitsio: true
 GIF save with cgif: true
-selected Magick package: MagickCore (dynamic module: true)
+selected Magick package: MagickCore (dynamic module)
 Magick API version: magick6
 Magick load: true
 Magick save: true
```

### CODE REVIEW

**Comment by kleisauke** [comment]
The above diff is with dynamic modules enabled, with `-Dmodules=disabled` I see:

<details>
  <summary>Details</summary>

```
enable debug: false
enable deprecated: false
enable modules: false
enable RAD load/save: true
enable Analyze7 load/save: true
enable PPM load/save: true
enable GIF load: true
use fftw for FFTs: true
accelerate loops with ORC: true
ICC profile support with lcms: true
zlib: true
text rendering with pangocairo: true
font file support with fontconfig: true
EXIF metadata support with libexif: true
JPEG load/save with libjpeg: true
JXL load/save with libjxl: true
JPEG2000 load/save with OpenJPEG: true
PNG load/save with libspng: true
PNG load/save with libpng: false
selected quantisation package: imagequant
TIFF load/save with libtiff: true
image pyramid save with libgsf: true
HEIC/AVIF load/save with libheif: true
WebP load/save with libwebp: true
PDF load with PDFium: false
PDF load with poppler-glib: true
SVG load with librsvg: true
EXR load with OpenEXR: true
OpenSlide load: true
Matlab load with libmatio: true
NIfTI load/save with niftiio: true
FITS load/save with cfitsio: true
GIF save with cgif: true
selected Magick package: MagickCore
Magick API version: magick6
Magick load: true
Magick save: true
```
</details>

**Comment by kleisauke** [comment]
Applying this patch would make the `vips --vips-config` output indetical:

<details>
  <summary>Patch</summary>
  
```diff
--- a/libvips/include/vips/meson.build
+++ b/libvips/include/vips/meson.build
@@ -92,7 +92,10 @@ foreach _, section : build_summary
            continue
         endif
 
-        vips_verbose_config += '@0@: @1@@2@'.format(key, arr[0], arr.length() > 1 ? arr[1] : '')
+        vips_verbose_config += '@0@: @1@@2@@3@@4@'.format(key, arr[0], 
+            arr.length() > 1 ? arr[1] : '',
+            arr.length() > 2 ? arr[2] : '',
+            arr.length() > 3 ? arr[3] : '')
     endforeach
 endforeach
 
--- a/meson.build
+++ b/meson.build
@@ -648,25 +648,25 @@ build_summary = {
     },
   'External image format libraries':
     {'JPEG load/save with libjpeg': [libjpeg_dep.found()],
-     'JXL load/save with libjxl': [libjxl_found, libjxl_module ? ' (dynamic module)' : ''],
+     'JXL load/save with libjxl': [libjxl_found, ' (dynamic module: ', libjxl_module, ')'],
      'JPEG2000 load/save with OpenJPEG': [libopenjp2_dep.found()],
      'PNG load/save with libspng': [spng_found],
      'PNG load/save with libpng': [png_dep.found()],
      'selected quantisation package': [quantisation_package.found() ? quantisation_package.name() : 'none'],
      'TIFF load/save with libtiff': [libtiff_dep.found()],
      'image pyramid save with libgsf': [gsf_dep.found()],
-     'HEIC/AVIF load/save with libheif': [libheif_dep.found(), libheif_module ? ' (dynamic module)' : ''],
+     'HEIC/AVIF load/save with libheif': [libheif_dep.found(), ' (dynamic module: ', libheif_module, ')'],
      'WebP load/save with libwebp': [libwebp_dep.found()],
      'PDF load with PDFium': [pdfium_dep.found()],
-     'PDF load with poppler-glib': [libpoppler_found, libpoppler_module ? ' (dynamic module)' : ''],
+     'PDF load with poppler-glib': [libpoppler_found, ' (dynamic module: ', libpoppler_module, ')'],
      'SVG load with librsvg': [librsvg_found],
      'EXR load with OpenEXR': [openexr_dep.found()],
-     'OpenSlide load': [openslide_dep.found(), openslide_module ? ' (dynamic module)' : ''],
+     'OpenSlide load': [openslide_dep.found(), ' (dynamic module: ', openslide_module, ')'],
      'Matlab load with libmatio': [matio_dep.found()],
      'NIfTI load/save with niftiio': [libnifti_dep.found()],
      'FITS load/save with cfitsio': [cfitsio_dep.found()],
      'GIF save with cgif': [cgif_dep.found()],
-     'selected Magick package': [magick_found ? magick_dep.name() : 'none', magick_module ? ' (dynamic module)' : ''],
+     'selected Magick package': [magick_found ? magick_dep.name() : 'none', ' (dynamic module: ', magick_module, ')'],
      'Magick API version': [magick_found ? 'magick' + magick_dep.version().split('.')[0] : 'none'],
      'Magick load': [magick_found and 'load' in get_option('magick-features')],
      'Magick save': [magick_found and 'save' in get_option('magick-features')],
```
</details>

@jcupitt What do you prefer? Using `(dynamic module: YES/NO)` in the build summary or just `(dynamic module)` if it is built as a dynamic module (and omitted if not). The latter approach would also change the output in `vips --vips-config`, as seen in the diffs above.

**Comment by jcupitt** [comment]
Both seem fine to me. Pick what you think is best!

I suppose YES/NO might be simpler to parse if we want to use this output in a script, but if we wanted to be easy to parse we should output something like JSON. So I think it doesn't matter.

**Comment by kleisauke** [comment]
OK, commit a6df3e1887da78aae0464fbb1909cc960cde55b9 uses YES/NO to indicate support for dynamic modules. I now see:
Screenshot from 2022-07-29 12-07-48
And `vips --vips-config` is identical.

**Comment by jcupitt** [comment]
Nice, less code is always good.

**Pull request merged**
