### PR TITLE
Update libnsgif

### PR DESCRIPTION
**Pull request by tlsa**
This series syncs with the [upstream libnsgif](http://git.netsurf-browser.org/libnsgif.git/)'s changes to optimize LZW decompression.

Patches created with the following (from `libnsgif/src` directory):

```
git format-patch --relative bba28df0cc0c75338a63645c6a55aebfebe91c74
```

And applied with:

```
git am --directory=libvips/foreign/libnsgif/ ../libnsgif/src/*.patch
```

### CODE REVIEW

**Comment by jcupitt** [comment]
Very cool, thank you @tlsa !

We have `update.sh` in `libvips/foreign/libnsgif` which attempts to update our copy of libnsgif from your git master. Would running that have the save effect as this PR?

**Comment by tlsa** [comment]
> Very cool, thank you @tlsa !
> 
> We have `update.sh` in `libvips/foreign/libnsgif` which attempts to update our copy of libnsgif from your git master. Would running that have the save effect as this PR?

Oh, I did not see that script.  It should have the same ultimate effect, although it would be harder to inspect which commits you have from upstream from looking at the log.

**Comment by jcupitt** [comment]
OK, let's merge this and then try `update.sh` as well to make sure it's all up to date. Thanks for the PR!

**Comment by jcupitt** [comment]
Updated from your repo: https://github.com/libvips/libvips/commit/4cd5da230314f2009bb15d152845d573330c5e31

**Pull request merged**
