### PR TITLE
webpload: prevent divide-by-zero when blending pixels

### PR DESCRIPTION
**Pull request by lovell**
Adds a test case to prevent future regression.

As discussed in commit 6eaf1ed

### CODE REVIEW

**Comment by jcupitt** [comment]
Yes, good idea to have a test. This is my fault, sorry :( I'll start preparing 8.10.5. 

@kleisauke, any thoughts for other urgent stuff we should include?

**Comment by kleisauke** [comment]
Not that I know, and sorry for not having caught this earlier.

**Comment by jcupitt** [comment]
OK, we have https://github.com/libvips/libvips/releases/tag/v8.10.5

I'll do some win builds and then remove the pre-release tag.

**Comment by kleisauke** [comment]
(Less urgent, but nice to have, is testing https://github.com/libvips/libvips/issues/1808#issuecomment-745392356. However, such AVIF images [cannot be loaded in Chrome](https://github.com/chromium/chromium/blob/c0fe1d638d94c08b80e7033ede733e63a30bbf0d/third_party/blink/renderer/platform/image-decoders/avif/avif_image_decoder.cc#L571-L577) either, so it does not block AVIF support in the prebuilt binaries, I think)

**Comment by jcupitt** [comment]
Having to decode the image just to get the header fields feels very wrong :( Perhaps there's some other way we could fix the clap box issue?

**Comment by kleisauke** [comment]
NetVips unit tests pass on Windows with the [MXE-based v8.10.5 builds](https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.5). I still need to check Linux and macOS, but I don't think this will bring any regression.

@lovell The [`-build2` suffix](https://github.com/lovell/sharp-libvips/blob/1fdeeb752ab37bbf1bbc3d49e38689d6ed7c476f/build/win.sh#L26) needs to be removed from sharp-libvips Windows build script in order to pass CI.

**Pull request merged**
