### PR TITLE
add suport for N colour ICC profiles

### PR DESCRIPTION
**Pull request by jcupitt**
This seems to export to 6clr CMYK correctly. We'll need something fancier for import, and for more generic N colour profiles.

See https://github.com/libvips/libvips/discussions/3045 for a sample 6 clr profile.

### CODE REVIEW

**Comment by jcupitt** [comment]
Sample output:

```
$ vips icc_export k2.jpg x.tif --output-profile 6clr-test.icc 
$ tiffinfo x.tif
TIFF Directory at offset 0x17817608 (10fe008)
  Image Width: 1450 Image Length: 2048
  Resolution: 72.009, 72.009 pixels/inch
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: separated
  Extra Samples: 2<unassoc-alpha, unassoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 6
  Rows/Strip: 128
  Planar Configuration: single image plane
  InkSet: 1
  ICC Profile: <present>, 13739188 bytes
``

**Comment by jcupitt** [comment]
OK, seems to all work, ready for testing. @ryanobeirne if you could check the output,. that'd be great.

With this test image:

http://www.rollthepotato.net/~john/theo-kickbike.jpg

I ran:

```
$ vips icc_export theo-kickbike.jpg theo-kickbike.tif --output-profile 6clr-test.icc 
```

To make:

http://www.rollthepotato.net/~john/theo-kickbike.tif

You can import the image again with:

```
$ vips icc_import theo-kickbike.tif x.jpg
```

To make:

x

There blacks look off, but maybe that's expected behaviour?

**Comment by ryanobeirne** [comment]
This is great work, thanks for this. The 6clr icc profile I provided is for a textile printing device with a very light minimum L* value, so this round-trip output is what I would expect.

I have at least one software that handles the 6-color tiff as expected, so this is great news. However, GIMP and Photoshop interpret the image as CMYK with a single Alpha channel and claims the embedded ICC profile is invalid, so I'm not sure what's going on there. Maybe it expects to have the interpretation as `MULTIBAND` rather than `CMYK`?

I'll take a deeper dive in the next few days.

**Comment by jcupitt** [comment]
I think GIMP at least just doesn't support 6 colour separations. `eog` is the same.

I don't know what Photoshop support for N-colour separations is like :( I'll be interested to know how your tests come out.

**Comment by ryanobeirne** [comment]
GIMP for sure doesn't support editing anything other than RGB, but it will convert from CMYK upon import. I think that's what it attempted to do here, but gave the error:

    Execution error for procedure 'gimp-image-set-color-profile':
    ICC profile validation failed: Color profile is not for RGB color space

It then showed the converted RGB image with with a single alpha channel:

Screen Shot 2022-09-14 at 1 17 57 PM

Photoshop imported the 6CLR image as CMYK with a single alpha channel, but gave the error:

    The embedded ICC profile cannot be used because the ICC profile is invalid. Ignoring the profile.

Screen Shot 2022-09-14 at 10 08 57 AM

The data is mostly there, maybe missing a channel, but the channels are out of order. It's hard to tell what's going on exactly.

****

I've seen Photoshop handle 6-Color images two ways:

1. True "Multichannel" with embedded 6CLR profiles:

Screen Shot 2022-09-14 at 1 35 29 PM

2. CMYK with 2 "Spot" channels:

Screen Shot 2022-09-14 at 1 39 56 PM

Photoshop will only allow you to export to TIFF with the 2nd option, which is what I use most of the time. The only options for saving as multichannel with the 1st option are PSD and DCS(EPS).

With either method, I think the expectation is that the first 4 channels are always CMYK.

**Comment by ryanobeirne** [comment]
Here are a couple sets of RGB images converted to `6clr-test.icc`. I included the PSD, DCS/EPS, and TIFF versions of each. Not sure how helpful the DCS/EPS will be. I don't know much about that format.

For the TIFFs, I converted the RGB images to the 6CLR profile in Photoshop, then marked as CMYK and included the 2 spot channels (Red, Green).

[theo-kickbike-6clr.zip](https://docs.ryanobeirne.com/public/theo-kickbike-6clr.zip)

[6clr-ps.zip](https://docs.ryanobeirne.com/public/6clr-ps.zip)

**Comment by jcupitt** [comment]
I tried making the libvips 6clr TIFF output a bit more like the photoshop one:

http://www.rollthepotato.net/~john/theo-kickbike2.tif

Would you be able to test it? It probably won't work, but you never know.

**Comment by jcupitt** [comment]
No, there's nothing in TIFF about spot colours -- it just has SEPARATED (meaning, some kind of set of inks) with the first four as CMYK.

If you run `tiffinfo` on the photoshop output you see:

```
$ tiffinfo theo-kickbike-6clr-cmyk.tif | more
TIFF Directory at offset 0x8 (8)
  Subfile Type: (0 = 0x0)
  Image Width: 1244 Image Length: 1866
  Resolution: 240, 240 pixels/inch
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: separated
  Extra Samples: 2<unspecified, unspecified>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 6
  Rows/Strip: 1866
  Planar Configuration: single image plane
  Make: Canon
  Model: Canon EOS 30D
  Software: Adobe Photoshop 23.5 (Macintosh)
  DateTime: 2022:09:14 16:49:52
  Artist: unknown
  XMLPacket (XMP Metadata):
... snip ... pages of photoshop XML metadata
  RichTIFFIPTC Data: <present>, 224 bytes
  Photoshop Data: <present>, 11772 bytes
  EXIFIFDOffset: 0xd517b8
TIFF Directory at offset 0x13965240 (d517b8)
  ExposureTime: 0.006250
  FNumber: 4.500000
  ExposureProgram: 4
  ISOSpeedRatings: 100
  ExifVersion: 0x30,0x32,0x32,0x31
  DateTimeOriginal: 2007:09:23 13:39:12
  DateTimeDigitized: 2007:09:23 13:39:12
  ShutterSpeedValue: 7.321928
  ApertureValue: 4.339850
  ExposureBiasValue: 0.000000
  MaxApertureValue: 4.000000
  MeteringMode: 5
  Flash: 16
  FocalLength: 98.000000
  ColorSpace: 65535
  PixelXDimension: 1244
  PixelYDimension: 1866
  FocalPlaneXResolution: 3959.322021
  FocalPlaneYResolution: 3959.322021
  FocalPlaneResolutionUnit: 2
  CustomRendered: 0
  ExposureMode: 0
  WhiteBalance: 0
  SceneCaptureType: 0
```

The key fields are:

```
  Photometric Interpretation: separated
  Extra Samples: 2<unspecified, unspecified>
  Samples/Pixel: 6
```

So a separated image with two additional channels. I suppose the extra stuff in the "Photoshop Data" tag will say how to map those to extra colour channels.

The vips output is:

```
$ tiffinfo theo-kickbike.tif 
TIFF Directory at offset 0x13927832 (d48598)
  Image Width: 1244 Image Length: 1866
  Resolution: 240, 240 pixels/inch
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: separated
  Extra Samples: 2<unspecified, unspecified>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 6
  Rows/Strip: 128
  Planar Configuration: single image plane
```

So the key fields match, but there's no extra Photoshop Data tag to say how to interpret the extra channels.

**Comment by jcupitt** [comment]
... now I look I realize I stripped the ICC profile as well! duh.

Could you try importing `theo-kickbike3.tif` using your 6 colour profile?

**Comment by ryanobeirne** [comment]
> Could you try importing theo-kickbike3.tif using your 6 colour profile?

How do you mean exactly?

**Comment by jcupitt** [comment]
Sorry, I don't know photoshop, but after loading, can you somehow attach a profile to the image?

**Comment by ryanobeirne** [comment]
Got it, so...

In Photoshop, I can import the image as CMYK, then mark it as "Multichannel", but in that mode, Photoshop doesn't let you do any ICC transforms or even attach a profile. I'm not sure why that is, but it probably has something to do with there not being a lot of software support for NCLR profiles in general.

Regardless, at this point vips/lcms has presumably done all the ICC transforms so attaching the profile is only helpful if you plan to do additional ICC transforms.

I think I'd like to test the conversion to a CIELab TIFF through the 6CLR profile. I know Photoshop handles Lab TIFFs well, and I think this may tell us a bit more. So for your original image `theo-kickbike.jpg` as input:

    AdobeRGB(1998) -> 6clr-test.icc -> Lab TIFF

You don't need to embed profiles with Lab colorspaces because Lab is the Profile Connection Space in this case. So if you wanted to do more color transforms at that point, this is how I would do it.

I'm not sure exactly how to do this with vips, but I think it should be fairly straightforward?

***

For me personally, my end goals are to be able to convert images to 6CLR profiles and separate each channel to their own bitmaps. But really I am just excited to have _any_ support for NCLR profiles. This is really looking great!

**Comment by jcupitt** [comment]
I had another go ... here's a version with the profile embedded and the tags matching photoshop. Is there an error on load?

http://www.rollthepotato.net/~john/theo-kickbike4.tif

**Comment by jcupitt** [comment]
Yes, libvips will make a CIELAB TIFF from that saved TIFF file, but I don't know if Photoshop will. It'll look just like that washed out RGB I made above ^^^. Just do:

```
$ vips icc_import theo-kickbike4.tif x.tif 
$ vipsheader x.tif
x.tif: 1244x1866 float, 3 bands, lab, tiffload
```

It's a float TIFF, I don't know if photoshop supports them.

**Comment by ryanobeirne** [comment]
> I had another go ... here's a version with the profile embedded and the tags matching photoshop. Is there an error on load?
> 
> http://www.rollthepotato.net/~john/theo-kickbike4.tif

Yes, still gives the same result with the 'invalid profile' error. Again, this is probably because it's tagged as a CMYK image with a 6CLR profile. I don't know that I would be too concerned about how Photoshop handles it, because frankly, it's never been that great. As long as the CMYK+RG data is all there and properly transformed through ICC, that should be the standard.

I think the real test will be how vips goes round-trip from RGB to 6CLR/Lab and back to RGB. I should be able to test this empirically without Photoshop, but may take me a while to sort out how.

I'll take a look at the Lab TIFF soon.

**Comment by jcupitt** [comment]
Ah shame. I think that's all we can do with photoshop compat, without a lot of work.

Roundtripping through CIELAB is easy, just:

```
$ vips icc_export theo-kickbike.jpg x.v --output-profile 6clr-test.icc 
$ vips icc_import x.v x.jpg
```

The first line will turn the sRGB JPEG into PCS (CIELAB, by default, but vips supports CIEXYZ as well), then export to 6clr device space. The second line will import from 6clr back to CIELAB PCS, then transform to sRGB and save. Overall it's:

sRGB -> CIELAB -> 6clr -> CIELAB -> sRGB

You get the slightly washed out JPG I posted above. It supports 16-bit too, so:

```
$ vips icc_export theo-kickbike.jpg x.v --output-profile 6clr-test.icc --depth 16
$ vips icc_import x.v x.jpg
```

But the results will be very similar.

**Comment by ryanobeirne** [comment]
I haven't forgot about this. I will review sometime this week.

**Comment by ryanobeirne** [comment]
> I tried making the libvips 6clr TIFF output a bit more like the photoshop one:
> 
> http://www.rollthepotato.net/~john/theo-kickbike2.tif
> 
> Would you be able to test it? It probably won't work, but you never know.
> 
> (no inkset tag, use unspecified for the extra bands)

@jcupitt can you explain what you did here? Did you edit the TIFF tags manually?

**Comment by jcupitt** [comment]
I just commented out the bits of the libvips TIFF writer that wrote the tags photoshop seemed to dislike. These changes are not part of this PR, they'd need more work.

**Comment by ryanobeirne** [comment]
Got it. Do you still have those commented bits? Can you post a diff patch? I want to try it with a handful of different images to make sure we're getting what we expect.

**Comment by jcupitt** [comment]
I think it was just this:

```diff
diff --git a/libvips/foreign/vips2tiff.c b/libvips/foreign/vips2tiff.c
index 058cece76..876a43d03 100644
--- a/libvips/foreign/vips2tiff.c
+++ b/libvips/foreign/vips2tiff.c
@@ -602,6 +602,8 @@ wtiff_embed_photoshop( Wtiff *wtiff, TIFF *tif )
 static int
 wtiff_embed_imagedescription( Wtiff *wtiff, TIFF *tif )
 {
+        return( 0 );
+
        if( wtiff->properties ) {
                char *doc;
 
@@ -764,7 +766,7 @@ wtiff_write_header( Wtiff *wtiff, Layer *layer )
                else if( wtiff->ready->Type == VIPS_INTERPRETATION_CMYK &&
                        wtiff->ready->Bands >= 4 ) {
                        photometric = PHOTOMETRIC_SEPARATED;
-                       TIFFSetField( tif, TIFFTAG_INKSET, INKSET_CMYK );
+                       // TIFFSetField( tif, TIFFTAG_INKSET, INKSET_CMYK );
                        colour_bands = 4;
                }
                else if( wtiff->compression == COMPRESSION_JPEG &&
@@ -803,9 +805,10 @@ wtiff_write_header( Wtiff *wtiff, Layer *layer )
                         * we are premultiplying.
                         */
                        for( i = 0; i < alpha_bands; i++ )
-                               v[i] = i == 0 && wtiff->premultiply ? 
-                                       EXTRASAMPLE_ASSOCALPHA :
-                                       EXTRASAMPLE_UNASSALPHA;
+                               v[i] =  EXTRASAMPLE_UNSPECIFIED;
+                               //v[i] = i == 0 && wtiff->premultiply ? 
+                                       //EXTRASAMPLE_ASSOCALPHA :
+                                       //EXTRASAMPLE_UNASSALPHA;
                        TIFFSetField( tif, 
                                TIFFTAG_EXTRASAMPLES, alpha_bands, v );
                }
```

**Comment by jcupitt** [comment]
Let's merge this work and try to improve the tiff writer tags in another PR. Please open a new issue if there are any problems.

**Pull request merged**
