### PR TITLE
make jp2kload work with the openjpeg test images

### PR DESCRIPTION
**Pull request by jcupitt**
We were not taking account of x0/y0 correctly.

See https://github.com/libvips/libvips/issues/4154

Thanks @mika-fischer

### CODE REVIEW

**Comment by jcupitt** [comment]
Test data here:

https://github.com/uclouvain/openjpeg-data/tree/master/baseline/nonregression

With this PR, we now load `Bretagne2_4.j2k` correctly. 

`Bretagne2_1.j2k` is still crashing argh.

**Comment by jcupitt** [comment]
OK, this now seems to load all the openjpeg test images correctly. 

Thanks again for reporting this, @mika-fischer 

This will be a pain to review :( sorry.

I added two tricky jp2k images from the openjpeg set to our test suite.

**Comment by kleisauke** [comment]
Perhaps this should target the [`8.15`](https://github.com/libvips/libvips/tree/8.15) branch instead? Of course, I can also backport it with a follow-up PR if that's easier. 

FWIW, LLVM does this very neatly with a bot that automates the entire process via `/cherry-pick <commit> <...>`.
https://llvm.org/docs/GitHub.html#backporting-fixes-to-the-release-branches
https://github.com/llvm/llvm-project/blob/main/.github/workflows/issue-release-workflow.yml

I was thinking about adopting a similar approach for libvips, which would avoid the need to retarget PRs and regularly merging release branches back into the master branch.

> This will be a pain to review :( sorry.

Don't worry, reviewing this with the `Hide whitespace changes` option makes it a bit easier.

**Comment by jcupitt** [comment]
It feels like a relatively large change, so I was thinking 8.16 would be a better place for it.

I'll have a look at the LLVM doc, thanks!

> Unfortunately, I still get crashes with the following files

Oh poop. I'll have a look.

I noticed imagemagick gets quite a few of the openjpeg test files wrong too, fwiw.

**Comment by mika-fischer** [comment]
I feel your pain 😬

Just to be clear, I don't really care whether vips can read any of these files correctly. It just should not crash, since we use vips as a library...

**Comment by jcupitt** [comment]
I agree it shouldn't crash.

You could just disable the libvips openjpeg loader, of course, that would probably be a safer fix. If you set the `VIPS_BLOCK_UNTRUSTED` env var, libvips won't run any loaders we haven't fuzzed ourselves.

**Comment by mika-fischer** [comment]
> You could just disable the libvips openjpeg loader, of course, that would probably be a safer fix.

Sure, that's what we did for the moment (falling back to ffmpeg). But of course one of the reasons we use vips in the first place is to be able to read formats like JPEG2000.

> If you set the `VIPS_BLOCK_UNTRUSTED` env var, libvips won't run any loaders we haven't fuzzed ourselves.

I see, but we need JPEG2000, JPEG-XL & PPM, which we would lose that way, so that's not really a good option...

**Comment by jcupitt** [comment]
It's now detecting when decoded pixels don't match the jpeg200 header and flagging an error, which seems to fix that set of crashes.

**Comment by jcupitt** [comment]
> we need JPEG2000, JPEG-XL & PPM,

Ah OK. As long as your users aren't uploading these strange jpeg2000 files, then it should work now.

**Comment by mika-fischer** [comment]
Great, thanks! I can confirm that the crashes are all gone and there are no valgrind warnings for the whole openjpeg folder.

**Comment by jcupitt** [comment]
Great! Thanks for testing @mika-fischer, and thanks for reporting this.

**Review by kleisauke — APPROVED** [review]
LGTM!

**Pull request merged**
