### PR TITLE
Travis fixes

### PR DESCRIPTION
**Pull request by kleisauke**
We ran the pyvips test suite on each commit instead of our own libvips test suite. 

I also moved the `apt-get` and `brew` commands in `before_install` to the APT addon section and increased the `magickload`/`magicksave` BMP threshold because it failed on Ubuntu 16.04.

### CODE REVIEW

**Comment by kleisauke** [comment]
Travis build is failing:
```
test/test-suite/test_foreign.py:432: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <test_foreign.TestForeign instance at 0x7f03c71ec830>, format = '.bmp'
options = '', im = <pyvips.Image 1024x768 uchar, 3 bands, srgb>, thresh = 25
    def save_load_file(self, format, options, im, thresh):
        # yuk!
        # but we can't set format parameters for pyvips.Image.new_temp_file()
        filename = temp_filename(self.tempdir, format)
    
        im.write_to_file(filename + options)
        x = pyvips.Image.new_from_file(filename)
    
        assert im.width == x.width
        assert im.height == x.height
        assert im.bands == x.bands
        max_diff = (im - x).abs().max()
>       assert max_diff <= thresh
E       assert 250.0 <= 25
```

See [here](https://travis-ci.org/libvips/libvips/jobs/474361833#L2786) (`max_diff = 250.0`) and [here](https://travis-ci.org/kleisauke/libvips/jobs/474354135#L2776) (`max_diff = 117.0`). Is there something wrong with `magicksave`?

**Comment by jcupitt** [comment]
I found 6.8.9-10, which seems to be the closest still in the archive:

http://ftp.acc.umu.se/mirror/imagemagick.org/ftp/releases/ImageMagick-6.8.9-10.tar.xz

And the tests pass with that. Mysterious!

**Comment by kleisauke** [comment]
I also can't reproduce this. I've tested it with a virtual machine (provided by DigitalOcean) on the same distribution as the Travis container (Ubuntu 16.04.5 LTS).

I'll try to run [this script](https://gist.github.com/kleisauke/0a9ee27407c5a6cbc57366f024228f18) in a virtual machine on the Google Compute Engine (Travis uses GCE as virtual machine).

**Comment by jcupitt** [comment]
Shall we merge? It does seem to be working now.

**Comment by kleisauke** [comment]
I haven't had time to further investigate why it fails on Travis, but it seems to work now with that PPA (so it looks like a magick issue).

You can merge this PR.

**Pull request merged**
