### PR TITLE
jpegsave: explicitly use 4:2:0 subsampling by default

### PR DESCRIPTION
**Pull request by kleisauke**
Unless saving with a quality setting of 90 or higher, or when chroma subsampling is explicitly disabled (`subsample_mode=off`).

This ensures compatibility with jpegli, which uses 4:4:4 by default.

See: https://github.com/libvips/libvips/issues/3922.

Targets the 8.15 branch.

### CODE REVIEW

**Comment by kleisauke** [comment]
FWIW, I haven't tested this properly yet, I'll do so later today.

**Comment by kleisauke** [comment]
Marking as draft due to this error:
```
E           pyvips.error.Error: unable to write to image
E             VipsJpeg: lib\jpegli\encode.cc:293: Sampling is not supported for simgle component image.
```
https://github.com/libvips/libvips/blob/009afbc00388eb46320187f3b556afaf1236f151/test/test-suite/test_foreign.py#L159

FWIW, `test_jpegsave` seems to pass now, it failed previously with:
```
>       assert len(q10_subsample_off) > len(q10)
E       assert 9459 > 9459
E        +  where 9459 = <snip />
E        +  and   9459 = <snip />

test\test-suite\test_foreign.py:292: AssertionError
```
https://github.com/libvips/libvips/blob/009afbc00388eb46320187f3b556afaf1236f151/test/test-suite/test_foreign.py#L292

**Comment by Snafuh** [comment]
I can confirm this fixes the issue with jpegli. ON/OFF is working as expected (4:2:0/4:4:4) and AUTO goes for 4:4:4 for Q>=90.

**Comment by kleisauke** [comment]
> Marking as draft due to this error:
> 
> ```
> E           pyvips.error.Error: unable to write to image
> E             VipsJpeg: lib\jpegli\encode.cc:293: Sampling is not supported for simgle component image.
> ```
> 
> https://github.com/libvips/libvips/blob/009afbc00388eb46320187f3b556afaf1236f151/test/test-suite/test_foreign.py#L159

This is no longer an issue with the latest revision of this PR which uses only 4:2:0 subsampling for multiband images.

I also opened PR https://github.com/libjxl/libjxl/pull/3457 to mirror this logic in jpegli.

**Comment by jcupitt** [comment]
```C
    if (subsample_mode == VIPS_FOREIGN_SUBSAMPLE_OFF ||
        (subsample_mode == VIPS_FOREIGN_SUBSAMPLE_AUTO &&
            qfac >= 90))
        for (int i = 0; i < in->Bands; i++) {
            cinfo->comp_info[i].h_samp_factor = 1;
            cinfo->comp_info[i].v_samp_factor = 1;
        }
    else if (in->Bands > 1) {
        /* Use 4:2:0 subsampling, but only if the image has more than
         * 1 band, since sampling factors are actually meaningless with
         * greyscale JPEG files.
         */
        cinfo->comp_info[0].h_samp_factor = 2;
        cinfo->comp_info[0].v_samp_factor = 2;

        /* Rest should have sampling factors 1,1.
         */
        for (int i = 1; i < in->Bands; i++) {
            cinfo->comp_info[i].h_samp_factor = 1;
            cinfo->comp_info[i].v_samp_factor = 1;
        }
    }
```

It looks odd to not have the bands=1 case covered.

How about:

```C
    if (subsample_mode == VIPS_FOREIGN_SUBSAMPLE_OFF ||
        in->Bands != 3 ||
        (subsample_mode == VIPS_FOREIGN_SUBSAMPLE_AUTO &&
            qfac >= 90))
        // no chroma subsample
        for (int i = 0; i < in->Bands; i++) {
            cinfo->comp_info[i].h_samp_factor = 1;
            cinfo->comp_info[i].v_samp_factor = 1;
        }
    else {
        // chroma subsample
        cinfo->comp_info[0].h_samp_factor = 2;
        cinfo->comp_info[0].v_samp_factor = 2;

        for (int i = 1; i < in->Bands; i++) {
            cinfo->comp_info[i].h_samp_factor = 1;
            cinfo->comp_info[i].v_samp_factor = 1;
        }
    }
```

That would make it clear what happens for CMYK JPEG as well.

Though looking at the libjpeg docs they say:

```
int h_samp_factor
int v_samp_factor
        Horizontal and vertical sampling factors for the component; must
        be 1..4 according to the JPEG standard.  Note that larger sampling
        factors indicate a higher-resolution component; many people find
        this behavior quite unintuitive.  The default values are 2,2 for
        luminance components and 1,1 for chrominance components, except
        for grayscale where 1,1 is used.

```

So the `jpeg_set_defaults(cinfo);` should have set 2,1,1 (for three bands images), 1 for greyscale, and 1,1,1,1 for CMYK. Doesn't that mean we don't need the `else{}` case here?

**Comment by jcupitt** [comment]
Ah I think I see, the `else{}` case is for jpegli which strangely does not match libjpeg behaviour for default chroma subsampling.

**Comment by kleisauke** [comment]
I've incorporated your suggestion. I'm not sure why jpegli doesn't match libjpeg's behaviour for default chroma subsampling. Perhaps that was done intentionally?

Of course, this PR might not be needed if jpegli uses 4:2:0 subsampling by default for 3 band images.

**Comment by kleisauke** [comment]
> I also opened PR [libjxl/libjxl#3457](https://github.com/libjxl/libjxl/pull/3457) to mirror this logic in jpegli.

This PR has just been merged. I think the `in->Bands != 3` condition is still necessary for CMYK save.

**Comment by jcupitt** [comment]
Ooop! Sorry I've been distracted with other stuff.

Thank you for fixing this!

**Comment by kleisauke** [comment]
> Of course, this PR might not be needed if jpegli uses 4:2:0 subsampling by default for 3 band images.

https://github.com/libjxl/libjxl/pull/3507 :sweat_smile:

**Comment by jcupitt** [comment]
I saw! But it's probably safest for us to set it anyway.

**Pull request merged**
