### PR TITLE
thumbnail: fix embedded ICC profile conversion

### PR DESCRIPTION
**Pull request by kleisauke**
Regressed since commit f0eb49364350c0b188f2531e4eb89ad90c825a7c (libvips 8.13.0).

`sample-xyb.jpg` was created with (with libjxl compiled from commit https://github.com/libjxl/libjxl/commit/225b688403ddfa6d9bc19a4ccbd0a49bfada686b):
```bash
# Lossy encode test image with cjxl
$ cjxl -d 1 --lossless_jpeg=0 test/test-suite/images/sample.jpg x.jxl
# Decode it to JPEG with the `--color_space XYB_Per` flag
$ djxl --color_space XYB_Per x.jxl test/test-suite/images/sample-xyb.jpg
```

The ICC profile that libjxl embedded is licensed under public domain (CC0).

### CODE REVIEW

**Comment by kleisauke** [comment]
CLI test cases:
<details>
  <summary>Details</summary>

`sample-xyb.jpg`:
```bash
$ cd test/test-suite/images
$ vipsthumbnail -s $(vipsheader -f width sample-xyb.jpg)x sample-xyb.jpg --export-profile srgb --intent perceptual

# Check colour distance
$ vips de00 sample.jpg tn_sample-xyb.jpg diff.v

# libvips 8.12.2 and this PR
$ vips max diff.v
9.504012

# libvips 8.13.0
$ vips max diff.v
39.877037
```

`cmyk5.jpg`:
```bash
# Examine image
$ vipsheader cmyk5.jpg
cmyk5.jpg: 3654x4577 uchar, 4 bands, cmyk, jpegload

# Examine ICC profile
$ exiftool -icc_profile:* cmyk5.jpg | grep Description
Profile Description             : U.S. Web Coated (SWOP) v2

# Thumbnail with built-in CMYK profile
$ vipsthumbnail -s $(vipsheader -f width cmyk5.jpg)x cmyk5.jpg --export-profile cmyk

(vipsthumbnail:23645): VIPS-WARNING **: 12:20:16.520: profile incompatible with image

# Examine output image
$ vipsheader tn_cmyk5.jpg
tn_cmyk5.jpg: 3654x4577 uchar, 4 bands, cmyk, jpegload

# Examine output ICC profile
$ exiftool -icc_profile:* tn_cmyk5.jpg | grep Description
Profile Description             : Chemical proof

# Check colour distance
$ vips de00 cmyk5.jpg tn_cmyk5.jpg diff.v

# libvips 8.12.2 and this PR
$ vips max diff.v
10.651659

# libvips 8.13.0
$ vips max diff.v
16.139965
```
</details>

I'm not sure about that `profile incompatible with image` warning within the CMYK test case, perhaps the user wanted to process in linear space (i.e. `icc_import` on the begin, `icc_export` on the end)?

**Comment by kleisauke** [comment]
This is ready for review now, diff is best viewed with the "Hide whitespace" option.

**Comment by kleisauke** [comment]
The `sample-xyb.jpg` with embedded ICC v4 profile is a useful way to check that ICC profiles are handled correctly. You'll get a green-ish image when the embedded profile is ignored.

On Firefox you need to set `gfx.color_management.enablev4` to `true` in `about:config` for these XYB JPEGs - see:
https://bugzilla.mozilla.org/show_bug.cgi?id=488800

**Comment by jcupitt** [comment]
Sorry for having sat on this. LGTM!

**Pull request merged**
