### PR TITLE
Handle error values when guessing interpretation

### PR DESCRIPTION
**Pull request by lovell**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37815 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37812

### CODE REVIEW

**Comment by jcupitt** [comment]
LGTM!

**Comment by lovell** [comment]
Thanks, should we backport this to 8.11 also?

**Comment by jcupitt** [comment]
Yes, it's a potential DoS I suppose. Let's do #2420 as well.

**Comment by jcupitt** [comment]
OK, backported to 8.11.

**Pull request merged**
