### PR TITLE
Optimize vips_foreign_save_cgif_set_transparent

### PR DESCRIPTION
**Pull request by DarthSim**
Hey there 👋

The current implementation of `vips_foreign_save_cgif_set_transparent` makes every pixel that is the same in the previous frame transparent. This approach is not very optimal.

The main purpose of making pixels transparent is to create sequences of identical indexes that are well compressed with LZW. But when we put a transparent index in the middle of a sequence of identical opaque pixels, we regrade compression instead of improving it.

The approach in this PR improves two things:
– Ensures that all sequences of transparent indexes are at least 2 indexes long. Single transparent pixels do not improve the compression.
– Ensures that sequences of identical indexes aren't broken with transparent indexes. The longer the sequence of identical pixels, the better the compression.

I tried to make the comments in the code as detailed as possible.

During my work, I made a collection of 27 animated GIFs. I won't upload them all here as they'll blow up the page 😅 But here's the table that compares the resulting file sizes gotten with the old and the new approaches:

|    | Old      | New      |
|----|----------|----------|
|  1 |    62054 |    59065 |
|  2 | 10072565 |  9934901 |
|  3 |  1949862 |  1873109 |
|  4 |  1532111 |  1555288 |
|  5 |   588365 |   588365 |
|  6 |  1560594 |  1535870 |
|  7 |   940467 |   849573 |
|  8 |  1834721 |  1688166 |
|  9 |  1839172 |  1880116 |
| 10 |   353883 |   338544 |
| 11 |  1087711 |  1027800 |
| 12 |   569076 |   567802 |
| 13 |  6468343 |  6069303 |
| 14 |  3670662 |  3501091 |
| 15 |  6354098 |  5634058 |
| 16 |  8952147 |  8382168 |
| 17 |  2477702 |  2160698 |
| 18 | 21725015 | 21070510 |
| 19 |     4021 |     4021 |
| 20 | 25080961 | 24944675 |
| 21 |  2857020 |  2856962 |
| 22 |  5633272 |  5469025 |
| 23 |    15800 |    15800 |
| 24 |  1859363 |  1927136 |
| 25 |   486429 |   482680 |
| 26 |  2582378 |  2539698 |
| 27 |  2376621 |  2166445 |

### CODE REVIEW

**Comment by lovell** [comment]
This looks great, clever idea, thank you Sergey. As part of this, did you experiment with longer sequences, perhaps at least 3 or 4 identical indexes (although I suspect this would make the implementation more complex for less gain)?

**Comment by DarthSim** [comment]
My first approach was just ensuring that transparent sequences are at least 3 pixels long, which was the optimal length. But for the approach from this PR, the optimal sequence length seems to be 2 pixels.

I updated the algorithm a bit to allow breaking sequences of identical indexes with long sequences of transparent indexes. Here's the new comparison table:

|    | Old       | New      |
|----|-----------|----------|
|  1 |     62054 |    58805 |
|  2 |  10072565 |  9935150 |
|  3 |   1949862 |  1873247 |
|  4 |   1532111 |  1546003 |
|  5 |    588365 |   588365 |
|  6 |   1560594 |  1525172 |
|  7 |    940467 |   849787 |
|  8 |   1834721 |  1687458 |
|  9 |   1839172 |  1879018 |
| 10 |    353883 |   342916 |
| 11 |   1087711 |  1031056 |
| 12 |    569076 |   567629 |
| 13 |   6468343 |  6053660 |
| 14 |   3670662 |  3501079 |
| 15 |   6354098 |  5634006 |
| 16 |   8952147 |  8384233 |
| 17 |   2477702 |  2160731 |
| 18 |  21725015 | 21082102 |
| 19 |      4021 |     4021 |
| 20 |  25080961 | 24943002 |
| 21 |   2857020 |  2856962 |
| 22 |   5633272 |  5468342 |
| 23 |     15800 |    15800 |
| 24 |   1859363 |  1844570 |
| 25 |    486429 |   482536 |
| 26 |   2582378 |  2532564 |
| 27 |   2376621 |  2165248 |

**Review by lovell — APPROVED** [review]
LGTM, thank you.

I'd quite like someone else to review this also, perhaps @dloebl may have comments/thoughts?

**Review by dloebl — APPROVED** [review]
Looks good! The approach makes sense to me 👍

I can see a nice improvement across the board. I've tested with 1000 animated GIFs and included the results from [gifsicle](https://github.com/kohler/gifsicle) for comparison:

**libvips [master](fcf3ff3167ec8524269b18b68e0d3335a0badb72):**
avg: 3.20 MB
median: 2.46 MB
max: 18.81 MB

**libvips feature/cgifsave-transparent-optimize:**
avg: 2.95 MB
median: 2.34 MB
max: 15.52 MB

**gifsicle -O3 (v1.93):**
avg: 2.42 MB
median: 1.98 MB
max: 11.35 MB

What's interesting, is that gifsicle is still better on average - this might be because of the set transparency or something else more encoding specific. Looks like gifsicle has an interesting/slightly different approach on the transparency optimization:
https://github.com/kohler/gifsicle/blob/bdac32963dca1b5b5134407a2034c900d576ae66/src/opttemplate.c#L759

But I think that's more something of a future improvement we could do to get closer to gifsicle.

**Comment by DarthSim** [comment]
With -O3, gifsicle tests two approaches and chooses one that is compressed better. We can't do so because we optimize transparency on the vips level and compress on the CGIF level.

**Review by kleisauke — APPROVED** [review]

**Pull request merged**
